[loggers]
keys=root,faq_app

[handlers]
keys=console

[formatters]
keys=default

[logger_root]
level=NOTSET
handlers=console

[logger_faq_app]
level=INFO
handlers=console
qualname=faq_app
propagate=0

[handler_console]
class=StreamHandler
level=INFO
formatter=default
args=(sys.stdout,)

[formatter_default]
format=%(asctime)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
