apiVersion: apps/v1
kind: Deployment
metadata:
  name: sail-faq-api
  namespace: oscar-dev
  labels:
    app: sail-faq-api
spec:
  replicas: 1  # Single instance
  selector:
    matchLabels:
      app: sail-faq-api
  template:
    metadata:
      labels:
        app: sail-faq-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: sail-faq-api
          image: earlybirdreal/sail-faq-api:a8cf433719750b646e04e9e7c271b5d6bf6fdeec
          env:
            - name: FAQ_AZURE_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: faq-azure-storage-secret
                  key: FAQ_AZURE_CONN_STRING
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: "490Mi"
            requests:
              cpu: "0.05"
              memory: "50Mi"
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: sail-faq-api-service
  namespace: oscar-dev
spec:
  selector:
    app: sail-faq-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sail-faq-api-route
  namespace: oscar-dev
spec:
  to:
    kind: Service
    name: sail-faq-api-service
  port:
    targetPort: 8080
  tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
